on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Debug info
        run: |
          if [ -n "${{ secrets.GH_PAT }}" ]; then
            echo "GH_PAT is set."
          else
            echo "GH_PAT is not set."
          fi

