name: Daily Auto Commit

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "kwaksh2319@gmail.com"
          git config --global user.name "kwaksh2319"
          git config --global credential.helper store

      - name: Create commit
        run: |
          echo "$(date)" >> daily_commit.txt
          git add daily_commit.txt
          git commit -m "Daily commit: $(date)"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
