name: Scheduled Jobs

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"

      - name: repository checkout
        uses: actions/checkout@v2
        with:
          repository: kwaksh2319/example
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          path: example

      - name: Add date and push
        run: |
          cd example
          date >> date.txt
          git add .
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git commit -am "Inject Date"
          git push
