on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "kwaksh2319@gmail.com"
          git config --global user.name "kwaksh2319"

      - name: Create commit
        run: |
          echo "$(date -u)" >> daily_commit.txt
          git add daily_commit.txt
          git commit -m "Daily commit: $(date -u)"
          
      - name: Push changes
        env:
          GH_PAT: ${{ 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}}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/kwaksh2319/example.git
          git push origin HEAD:master
