name: Daily Auto Commit

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "kwaksh2319@gmail.com"
          git config --global user.name "kwaksh2319"

      - name: Create commit
        run: |
          echo "$(date)" >> daily_commit.txt
          git add daily_commit.txt
          git commit -m "Daily commit: $(date)"
          git push
