name: Scheduled Jobs

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"

      - name: repository checkout
        uses: actions/checkout@v2
        with:
          repository: /kwaksh2319/example/tree/main/.github
          token: ${{ secrets.GH_PAT }}
          path: /example/tree/main/.github

      - name: Add date and push
        run: |
          cd infra-study
          date >> date.txt
          git add .
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git commit -am "Inject Date"
          git push
